points:
- x: 0.29264475743348983
  y: 0.03549060542797495
- x: 0.5915492957746479
  y: 0.037578288100208766
- x: 0.5837245696400626
  y: 0.3987473903966597
- x: 0.2942097026604069
  y: 0.40083507306889354
